services:
  - type: web
    name: distilbert-menstrual-phase-api
    runtime: python
    rootDir: backend

    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu
      python -m pip install --no-cache-dir -r requirements.txt

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: FRONTEND_ORIGIN
        value: https://malithi-gif.github.io

      - key: TOKENIZERS_PARALLELISM
        value: "false"

      - key: OMP_NUM_THREADS
        value: "1"

      - key: MKL_NUM_THREADS
        value: "1"

      - key: CUDA_VISIBLE_DEVICES
        value: ""