services:
  - type: web
    name: distilbert-menstrual-phase-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FRONTEND_ORIGIN
        value: https://malithi-gif.github.io
